### ISSUE TITLE
No text visible in window: Expose highlights?

### ISSUE THREAD

**Issue by Makaze** [NStefan002/screenkey.nvim#11]
### Problem

I can't see anything in the window on any theme. I'm not sure if it's a highlights issue or it's just not firing. How can I debug?

### Steps to reproduce

1. Use nvchad
2. `:Screenkey`
3. Start navigating
4. Nothing shows in the window

### Expected behavior

The keys show in the window

### Neovim version (`nvim -v`)

NVIM v0.10.0-dev-1405e5c AND v0.9.5

### Terminal name/version

alacritty 0.14.0-dev

**Comment by Makaze** [comment]
![screenkey_issue](https://github.com/NStefan002/screenkey.nvim/assets/2280429/8508bdf5-7bee-490c-8d6f-ba2a83d09101)
Demo of issue

**Comment by NStefan002** [comment]
> NVIM v0.10.0-dev-1405e5c AND v0.9.5

0.9.5 is not an issue since Screenkey requires the latest nightly build. See [requirements](https://github.com/NStefan002/screenkey.nvim?tab=readme-ov-file#%EF%B8%8F-requirements) for Screenkey. Also, try updating to the latest nightly, since the feature required for Screenkey was merged only three weeks ago.

**Comment by Makaze** [comment]
It works on nightly. Thanks.
