### ISSUE TITLE
[bug] Ctrl+/ displays as Ctrl+_ 

### ISSUE THREAD

**Issue by iamxiaojianzheng** [NStefan002/screenkey.nvim#30]
### Problem

![image](https://github.com/NStefan002/screenkey.nvim/assets/29248764/644cb62f-3f0f-4004-8a5f-af1911454fe2)

### Steps to reproduce

Just normal configuration

```lua
{
    "NStefan002/screenkey.nvim",
    lazy = false,
    version = "*", -- or branch = "dev", to use the latest commit
  },
```

### Neovim version (`nvim -v`)

NVIM v0.10.0

### Terminal name/version

Windows terminal 1.21.1382.0

**Comment by NStefan002** [comment]
Hi, thanks for reporting. There is a well-known and very old problem with terminal keycodes. Depending on the terminal emulator you're using and (maybe) OS, some keys and a combination of keys produce the same keycode. E.g. `<C-i>` and `<Tab>` produce the same keycode and they are impossible to differentiate in most of the terminal emulators (as far as I know). I don't know much about the history of this problem so I can't go too deep about this. 

Anyway, I tested `<C-/>` on my machine (Ubuntu 22.04, terminal: Wezterm) and it produces the correct output so I'm pretty sure this issue is not screenkey-related but rather it has to do with how your terminal emulator handles input.
